### ISSUE TITLE
[Feature Request] Kagi Translate support

### ISSUE THREAD

**Issue by nichu42** [jonas-w/share2kagi-android#1]
Absolutely love your app! Can you add support for translate.kagi.com?

**Comment by jonas-w** [comment]
@nichu42 thank you, glad to hear!

I took a quick glance at Kagi Translate, and it seems like Kagi uses POST requests (which means that the translated text can't be passed via the URL), so it might not be possible, but I'll definitely look into this.

EDIT: Just saw that it supports website translation, this one I can probably implement, but not text translation (from what I can see). Did you mean this?

**Comment by jonas-w** [comment]
I think I got it working (even with text translation)!

If you want to try, here is a debug build: [app-debug.zip](https://github.com/user-attachments/files/17670947/app-debug.zip) (I configured debug builds to look a bit differently, i.e. purple icon and named Kagi Summarizer (Debug)). Debug builds *are* slow, so selecting a language in the Selector might be jarring, but this won't be the case with release builds.

Before making a release, I'll test it also myself a bit more, and I'll also try to update the dependencies.

EDIT: Oops I think I broke the summary features in this version 😅 At least the translation feature seems to work

**Comment by nichu42** [comment]
It works. Fantastic! And yes, summary is broken now. But gladly, I still have the release version. 😅

**Comment by jonas-w** [comment]
Okay 😅 I think I found all bugs. I also renamed the App to Share2Kagi, as Kagi Summarizer wasn't "correct" anymore, added some example buttons for easier testing and updated the dependencies. Just for fun, I also added a reverse image search feature (only Image URLs for now) 😄


Here is the current release build if you want to give it another shot: [app-release.zip](https://github.com/user-attachments/files/17684779/app-release.zip) As I renamed the app, you can install this version in parallel with the version 2.0

If I don't find any further bugs, I'll probably release this version 'officially' on GitHub tomorrow


Wanted to update the dependencies and clean up the codebase since a while, but never really found the motivation, so thank you for the feature request!

**Comment by nichu42** [comment]
Awesome! I tested everything and did not encounter any problems. Thank you so much. Your app is a great companion on my mobile devices.

**Comment by jonas-w** [comment]
Have released version [3.0](https://github.com/jonas-w/share2kagi-android/releases/tag/3.0), nothing really changed since Sunday (except some really minor code refactoring and the version number).

Closing this now, thanks again!
